#Definindo o nome do Workflow
name: CI / CD Pipeline

#Definindo quando o Workflow será disparado
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

#Definindo os jobs que o Workflow executará
jobs:
  test_job:
    name: Executando o job teste
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: 'cidicley'
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      # Construção e execução do contêiner Docker
      - name: Build Docker Image
        run: |
          # Construir a imagem Docker
          docker build -t my-app .      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      # Rodar os testes dentro do contêiner
      - name: Run tests
        run: |
          dotnet test ./tests/FiapTechChallenge.Test/FiapTechChallenge.Test.csproj --configuration Release --logger "trx"

      - name: Build and push Docker images        
        uses: docker/build-push-action@v6.10.0
        with:
          context: .
          tags: 'cidicley/fiap-ghactions:latest'
          push: true
          
          
