#Definindo o nome do Workflow
name: CI / CD Pipeline

#Definindo quando o Workflow será disparado
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

#Definindo os jobs que o Workflow executará
jobs:
  test_job:
    name: Executando o job teste
    runs-on: ubuntu-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: 'cidicley'
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
